### ISSUE TITLE
Create poll UI

### ISSUE THREAD

**Issue by sophiajwitt** [CMU-313/spring23-nodebb-team-tbd#6]
front end implementation of poll feature, needs to communicate with the database
need separate UI for voters and creator, need feature button in post creation, and vote button and submit for voters.

Estimated effort: medium-high
Dependencies among tasks: create poll database
Milestone: Sprint 2
Acceptance criteria: task will be complete through user testing

**Comment by krpatel5657** [comment]
Closed by polls plugin installation
